### PR TITLE
Fixed an issue where parties will return null.

### PR DESCRIPTION
**Pull request by Lagggpixel**
Party plugin provider: PartiesParty
Class: PartiesPartyHandlerImpl
Fix provided: Non-null checks

### CODE REVIEW

**Comment by Plajer** [comment]
You've wrapped the whole null check inside another indentation block which decreases readability, consider returning prematurely instead of nesting (i.e. use if for the opposite case to return instantly).

Also as convenient as it looks I discourage using inline return if statement as seen in /PartiesPartyHandlerImpl.java. Consider including {} brackets for these if statements to ensure consistency across the codebase.

**Comment by Plajer** [comment]
Also not sure how getParty is used in the code but Max might consider replacing returning null with empty gameparty object if that is required to prevent any further issues.

**Comment by Lagggpixel** [comment]
> You've wrapped the whole null check inside another indentation block which decreases readability, consider returning prematurely instead of nesting (i.e. use if for the opposite case to return instantly).
> 
> Also as convenient as it looks I discourage using inline return if statement as seen in /PartiesPartyHandlerImpl.java. Consider including {} brackets for these if statements to ensure consistency across the codebase.

I don't think pre-mature returning should be used as even the party is found to be null, it could very well be that the party is empty when the player is still in a party(i.e. the player is the only player in the party), in which case the player could still be teleported into the arena.
Nesting would allow me to basically ignore that block of code for teleporting party members without having to stop the plugin entirely from stopping the player joining the game.

**Comment by Plajer** [comment]
All current implementations of isPlayerInParty method do already check for null value from getParty method so nevertheless this null check that nests the whole code even deeper is redundant.

**Comment by Plajer** [comment]
In case it doesn't it might just be better to implement additional null checks inside above-mentioned method just to avoid such unnecessary checks later in the future.

**Comment by Lagggpixel** [comment]
That new commit should remove all the redundant non-null checks.

**Comment by Tigerpanzer02** [comment]
@Lagggpixel nice to See your pr and effort, anyway the Code WE are developing with is located at the developement branch which you Need to select to modify the Code, AS the master branch IS outdated. Furthermore the Parties stuff is now located on the minigamesbox which you can find Here: https://github.com/Plugily-Projects/MiniGamesBox/tree/development/MiniGamesBox%20Classic/src/main/java/plugily/projects/minigamesbox/classic/handlers/party
If the issue is the same on the developement branch and minigamesbox I encourage you to create the prs for the correct branches ;) Thank you!

**Comment by Lagggpixel** [comment]
Alrighty

**Pull request closed without merging**
